server:
  port: 8080

spring:
  datasource:
    url: jdbc:mysql://localhost:3306/todo
    username:
    password:
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true

jwt:
  secret-key: ---
  expiration-time: 86400000 # ?? 24??